name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  go-module-workflow:
    name: go-module-workflow
    uses: ./.github/workflows/go-module-pr.yml
    with:
      OPERATOR_SDK_VERSION: "v1.22.2"
      GO_VERSION: "~1.18"
      RUN_UNIT_TESTS: true