name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: davgordo/github-workflows-operators/.github/workflows/pr-operator.yml@skip-package
    with:
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: false
      RUN_HELMCHART_TEST: false
      GO_VERSION: ~1.17