name: push
on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: davgordo/github-workflows-operators/.github/workflows/pr-operator.yml@skip-package
    with:
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: false
      PACKAGE_OPERATOR: false