name: push
on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  go-module-workflow:
    name: go-module-workflow
    uses: ./.github/workflows/go-module-release.yml
    with:
      OPERATOR_SDK_VERSION: "v1.22.2"
      GO_VERSION: "~1.18"
      RUN_UNIT_TESTS: true